# Generated by Django 5.1.4 on 2024-12-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('year', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.FloatField()),
            ],
        ),
    ]
