# Generated by Django 5.1.4 on 2024-12-31 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0002_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_game',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utpokerapp.host'),
        ),
    ]
