# Generated by Django 5.1.4 on 2025-01-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0003_alter_home_game_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('phone_number', models.FloatField()),
                ('year', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
