# Generated by Django 5.1.4 on 2025-01-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0004_contact_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
