# Generated by Django 5.1.4 on 2025-01-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0005_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(default='Empty'),
        ),
    ]
