# Generated by Django 5.1.4 on 2025-01-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0008_alter_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
