# Generated by Django 5.1.4 on 2025-01-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0010_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(default='No first name', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='No last name', max_length=200),
        ),
    ]
