# Generated by Django 5.1.4 on 2025-01-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0011_alter_contact_firstname_alter_contact_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=200),
        ),
    ]
