# Generated by Django 5.1.4 on 2025-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utpokerapp', '0012_alter_contact_firstname_alter_contact_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
